Name : Noora Aulia Hidayat

ID Num: 112710047

#1. What are the 4V's of big data, and why are they important in the context of data analysis?



4V

- Volume
  - volume is the scale of data. it can be Terabytes to exabytes. Big Data involving massive dataset that can't be handle and analyzed by traditional database system
- Velocity
  - the data is generated in real-time or near real-time. refers to the speed whice is data is collected or generated
- Variety
  - the diversity of datatype and sources. Structed, unstructured,text, multimedia
- Veracity
  - Unsertaintly due to data inconsistency & incompletness, ambiguities, latency, deception, model approximationsEnsuring data quality and reliability is essential in the big data ecosystem.

  Big Data is very important in the context of data analysis. first, data analyst need to use specialized tools and technologies that can efficiently process and analyze large datasets. second, for organization that needs real-time insights like analyze stock. Data analysts must be equipped to work with a wide range of data formats and integrate data from multiple sources to gain comprehensive insights.  Organizations use data analysis to gain a competitive advantage, identify market trends, and make informed strategic decisions. The "4Vs" help organizations assess their data capabilities and develop data strategies.
  



#2. Create a NumPy array from a Python list. please show 1D array, 2D  and 3D array.


In [ ]:
import numpy as np


In [ ]:
#1D Array
array1 = np.array([[74, 289, 2876, 12986]])
#2D Array
array2 = np.array([[1, 2], [3, 4]])
#3D Array
array3 = np.random.randint(3,99,(3,3))

In [ ]:
print("1D Array")
print(array1)


1D Array
[[   74   289  2876 12986]]


In [ ]:

print("2D Array")
print(array2)


2D Array
[[1 2]
 [3 4]]


In [ ]:
print("3D Array")
print(array3)

3D Array
[[77  5 33]
 [17 76 63]
 [60 94 55]]


#3. Perform basic arithmetic operations on arrays (addition, subtraction, multiplication, division). please show in a  2D array.

In [ ]:
array = np.array([[62, 2], [17, 4]])

addition_result = array + array

subtraction_result = array - array

scalar = 2
multiplication_result = array * scalar

divisor = 2
division_result = array / divisor

print("RESULT：")

print("Original :")
print(array)

print("Addition :")
print(addition_result)

print("Subtraction :")
print(subtraction_result)

print("Multiplication :")
print(multiplication_result)

print("Division :")
print(division_result)


RESULT：
Original :
[[62  2]
 [17  4]]
Addition :
[[124   4]
 [ 34   8]]
Subtraction :
[[0 0]
 [0 0]]
Multiplication :
[[124   4]
 [ 34   8]]
Division :
[[31.   1. ]
 [ 8.5  2. ]]
