<a href="https://colab.research.google.com/github/noora20FH/DataScience_Course/blob/BigData/HW_3_noora.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy Exercise

##1. Create a NumPy array containing integers from 0 to 9.

In [ ]:
import numpy as np
rng = np.random.default_rng(seed=10)
X = rng.integers(0, 10,(10, ))
print(X)

[7 9 2 2 7 8 5 1 8 5]


##2. Create a 5x5 random matrix.

In [ ]:
rng = np.random.default_rng(seed=42)
X = rng.integers(0, 25, (5,5))
print(X)

[[ 2 19 16 10 10]
 [21  2 17  5  2]
 [13 24 18 19 17]
 [19 12  3 20 11]
 [12  9  4 23 19]]


##3. Replace all odd numbers in a one-dimensional array with -1.

In [ ]:
rng = np.random.default_rng(seed=42)
Y = rng.integers(0, 50, (20,))
Y[Y % 2 != 0] = -1
print(Y)

[ 4 38 32 -1 -1 42  4 34 10  4 26 48 36 38 -1 -1 -1  6 -1 22]


#Pandas Exercises

In [ ]:
import pandas as pd

##1. Create a DataFrame containing name, age, and gender.

In [ ]:
import pandas as pd

data = pd.DataFrame([
    {'name': 'Anton', 'age': 46, 'gender': 'Male'},
    {'name': 'Nike', 'age': 34, 'gender': 'Female'},
    {'name': 'Salwa', 'age': 40, 'gender': 'Female'},
    {'name': 'Ima', 'age': 50, 'gender': 'Female'},
    {'name': 'Baihaq', 'age': 27, 'gender': 'Male'},
    {'name': 'Andre', 'age': 47, 'gender': 'Male'}
])

# Use .head() to limit the number of displayed rows
print(data.head(5))


     name  age  gender
0   Anton   46    Male
1    Nike   34  Female
2   Salwa   40  Female
3     Ima   50  Female
4  Baihaq   27    Male


##2. Read data from a CSV file and display the first 5 rows.


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/Academic Progress Report/Week4/president_heights.csv')


In [ ]:
print(df.head(5))

   order               name  height(cm)
0      1  George Washington         189
1      2         John Adams         170
2      3   Thomas Jefferson         189
3      4      James Madison         163
4      5       James Monroe         183


In [ ]:
import pandas as pd

data = pd.DataFrame([
    {'name': 'Anton', 'age': 46, 'gender': 'Male'},
    {'name': 'Nike', 'age': 34, 'gender': 'Female'},
    {'name': 'Salwa', 'age': 40, 'gender': 'Female'},
    {'name': 'Ima', 'age': 50, 'gender': 'Female'},
    {'name': 'Baihaq', 'age': 27, 'gender': 'Male'},
    {'name': 'Andre', 'age': 47, 'gender': 'Male'}
])

# Use .head() to limit the number of displayed rows
print(data.head(5))


     name  age  gender
0   Anton   46    Male
1    Nike   34  Female
2   Salwa   40  Female
3     Ima   50  Female
4  Baihaq   27    Male


##3. Select specific columns in the DataFrame.


In [ ]:
selected_column = df[['order','name']]
print(selected_column.to_string(index=False))

 order                   name
     1      George Washington
     2             John Adams
     3       Thomas Jefferson
     4          James Madison
     5           James Monroe
     6      John Quincy Adams
     7         Andrew Jackson
     8       Martin Van Buren
     9 William Henry Harrison
    10             John Tyler
    11          James K. Polk
    12         Zachary Taylor
    13       Millard Fillmore
    14        Franklin Pierce
    15         James Buchanan
    16        Abraham Lincoln
    17         Andrew Johnson
    18       Ulysses S. Grant
    19    Rutherford B. Hayes
    20      James A. Garfield
    21      Chester A. Arthur
    23      Benjamin Harrison
    25       William McKinley
    26     Theodore Roosevelt
    27    William Howard Taft
    28         Woodrow Wilson
    29      Warren G. Harding
    30        Calvin Coolidge
    31         Herbert Hoover
    32  Franklin D. Roosevelt
    33        Harry S. Truman
    34   Dwight D. Eisenhower
    35    

##4. Identify and handle missing values in the DataFrame.

In [ ]:
data2 = pd.DataFrame([
    {'name': 'Anton', 'age': 46, 'gender': 'Male'},
    {'name': 'Nike', 'age': 34, 'gender': 'Female'},
    {'name': 'Salwa', 'age': None, 'gender': 'Female'},
    {'name': 'Ima', 'age': 50, 'gender': 'Female'},
    {'name': 'Baihaq', 'age': 27, 'gender': 'Male'},
    {'name': 'Andre', 'age': None, 'gender': 'Male'}
])


missing_values = data2.isnull().sum()
print("Missing Values:\n", missing_values,"\n")


data.fillna(0, inplace=True)
print("DataFrame with Missing Values Filled:\n", data)

Missing Values:
 name      0
age       2
gender    0
dtype: int64 

DataFrame with Missing Values Filled:
      name   age  gender
0   Anton  46.0    Male
1    Nike  34.0  Female
2   Salwa   0.0  Female
3     Ima  50.0  Female
4  Baihaq  27.0    Male
5   Andre   0.0    Male
